acr debug

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -14,12 +14,12 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     
-      - name: Debug Secrets
-        run: echo "CLIENT_ID=${{ secrets.CLIENT_ID }}, TENANT_ID=${{ secrets.TENANT_ID }}, SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}"
-        env:
-          CLIENT_ID: ${{ secrets.CLIENT_ID }}
-          TENANT_ID: ${{ secrets.TENANT_ID }}
-          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
+      # - name: Debug Secrets
+      #   run: echo "CLIENT_ID=${{ secrets.CLIENT_ID }}, TENANT_ID=${{ secrets.TENANT_ID }}, SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}"
+      #   env:
+      #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
+      #     TENANT_ID: ${{ secrets.TENANT_ID }}
+      #     SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
 
       - name: Azure login
         uses: azure/login@v2
@@ -28,10 +28,11 @@ jobs:
           tenant-id: ${{ secrets.TENANT_ID }}
           subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
 
-
-      
       - name: Run Azure CLI Command
         run: az account show
+
+      - name: Verify ACR Existence
+        run: az acr show --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} || echo "ACR not found"
 
       - name: Login to Azure Container Registry (ACR)
         run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
