fix workflow ci

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -1,4 +1,4 @@
-name: Run Azure Login with OIDC and Automatic Build & Deploy to AKS
+name: Build & Push Notes API Image
 
 on:
   push:
@@ -9,42 +9,38 @@ permissions:
   id-token: write
   contents: read
 
+env:
+  ACR_NAME: notes
+  ACR_URL: notes.azurecr.io
+  APP_NAME: notes-api
+
 jobs:
-  build-and-deploy:
+  build-and-push:
     runs-on: ubuntu-latest
     steps:
-      - name: Azure login
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Azure Login with OIDC
         uses: azure/login@v2
         with:
           client-id: ${{ secrets.CLIENT_ID }}
           tenant-id: ${{ secrets.TENANT_ID }}
           subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
 
-      - name: Run Azure CLI Command
-        run: az account show
+      - name: Verify ACR
+        run: az acr show --name $ACR_NAME || echo "ACR not found"
 
-      - name: Verify ACR Existence
-        run: az acr show --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} || echo "ACR not found"
-
-      - name: Login to Azure Container Registry (ACR)
-        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
+      - name: Login to ACR
+        run: az acr login --name $ACR_NAME
 
       - name: Install Make
         run: sudo apt update && sudo apt install make -y
 
-      # - name: Install Docker
-      #   run: sudo apt update && sudo apt install docker -y
-
       - name: Build & Push Docker Image
-        run: make docker-build && make docker-push
+        run: |
+          docker build -t $ACR_URL/$APP_NAME:latest .
+          docker push $ACR_URL/$APP_NAME:latest
+          docker tag $ACR_URL/$APP_NAME:latest $ACR_URL/$APP_NAME:${{ github.sha }}
+          docker push $ACR_URL/$APP_NAME:${{ github.sha }}
 
-      - name: Set Up Kubernetes (kubectl)
-        uses: azure/setup-kubectl@v1
-        with:
-          version: latest
-
-      - name: Get AKS Credentials
-        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}
-
-      - name: Deploy to AKS
-        run: make deploy
